services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react_app
    container_name: react_app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - backend
    volumes:
      - .:/app
      - /app/client/node_modules
    command: bash -c "cd client && npm run start"
  rails_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails_app
    container_name: rails_app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - .:/app
      - /app/server/node_modules
    command: bash -c "cd server && bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0"
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: greatsage_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./server/tmp/db:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
